/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.117
 * Generated at: 2026-04-22 03:57:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.example.util.HtmlEscapeUtil;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.example.util.HtmlEscapeUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"zh-CN\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>登录 - 情绪垃圾桶</title>\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            margin: 0;\n");
      out.write("            min-height: 100vh;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            font-family: -apple-system, BlinkMacSystemFont, \"SF Pro Text\", \"Segoe UI\", sans-serif;\n");
      out.write("            background: linear-gradient(135deg, #dbeafe 0%, #e9d5ff 55%, #fbcfe8 100%);\n");
      out.write("            color: #111827;\n");
      out.write("        }\n");
      out.write("        .card {\n");
      out.write("            width: min(420px, 92vw);\n");
      out.write("            padding: 24px;\n");
      out.write("            border-radius: 22px;\n");
      out.write("            background: rgba(255, 255, 255, 0.2);\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.45);\n");
      out.write("            box-shadow: 0 12px 36px rgba(31, 41, 55, 0.14);\n");
      out.write("            backdrop-filter: blur(20px) saturate(1.2);\n");
      out.write("            -webkit-backdrop-filter: blur(20px) saturate(1.2);\n");
      out.write("        }\n");
      out.write("        h2 { margin: 0 0 8px; }\n");
      out.write("        p { margin: 0 0 16px; color: #4b5563; }\n");
      out.write("        label { display: block; margin: 10px 0 6px; }\n");
      out.write("        input {\n");
      out.write("            width: 100%;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("            border-radius: 14px;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.7);\n");
      out.write("            background: rgba(255, 255, 255, 0.8);\n");
      out.write("            padding: 10px 12px;\n");
      out.write("        }\n");
      out.write("        button {\n");
      out.write("            margin-top: 14px;\n");
      out.write("            width: 100%;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 14px;\n");
      out.write("            padding: 11px 12px;\n");
      out.write("            background: rgba(30, 64, 175, 0.84);\n");
      out.write("            color: #fff;\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("        .error {\n");
      out.write("            margin-top: 10px;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            padding: 10px 12px;\n");
      out.write("            color: #991b1b;\n");
      out.write("            background: rgba(254, 202, 202, 0.5);\n");
      out.write("            border: 1px solid rgba(239, 68, 68, 0.35);\n");
      out.write("        }\n");
      out.write("        .success {\n");
      out.write("            margin-top: 10px;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            padding: 10px 12px;\n");
      out.write("            color: #166534;\n");
      out.write("            background: rgba(187, 247, 208, 0.5);\n");
      out.write("            border: 1px solid rgba(34, 197, 94, 0.35);\n");
      out.write("        }\n");
      out.write("        .register-link {\n");
      out.write("            margin-top: 12px;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("        .register-link a {\n");
      out.write("            color: #1d4ed8;\n");
      out.write("            text-decoration: none;\n");
      out.write("        }\n");
      out.write("        .register-link a:hover {\n");
      out.write("            text-decoration: underline;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"card\">\n");
      out.write("    <h2>情绪垃圾桶</h2>\n");
      out.write("    <p>登录后即可匿名投递心情纸条。</p>\n");
      out.write("    <form method=\"post\" action=\"");
      out.print( request.getContextPath() );
      out.write("/login\">\n");
      out.write("        <label>用户名</label>\n");
      out.write("        <input type=\"text\" name=\"username\" required />\n");
      out.write("        <label>密码</label>\n");
      out.write("        <input type=\"password\" name=\"password\" required />\n");
      out.write("        <button type=\"submit\">进入匿名墙</button>\n");
      out.write("    </form>\n");
      out.write("    <div class=\"register-link\">\n");
      out.write("        还没有账号？<a href=\"");
      out.print( request.getContextPath() );
      out.write("/register\">去注册</a>\n");
      out.write("    </div>\n");
      out.write("    ");

        if ("1".equals(request.getParameter("registered"))) {
    
      out.write("\n");
      out.write("    <div class=\"success\">注册成功，请登录。</div>\n");
      out.write("    ");

        }
    
      out.write("\n");
      out.write("    ");

        Object error = request.getAttribute("error");
        if (error != null) {
    
      out.write("\n");
      out.write("    <div class=\"error\">");
      out.print( HtmlEscapeUtil.escape(error.toString()) );
      out.write("</div>\n");
      out.write("    ");

        }
    
      out.write("\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
