/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.117
 * Generated at: 2026-04-22 03:57:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.net.URLEncoder;
import com.example.model.StudentRecord;
import com.example.util.HtmlEscapeUtil;

public final class records_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("com.example.model.StudentRecord");
    _jspx_imports_classes.add("com.example.util.HtmlEscapeUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"zh-CN\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>情绪垃圾桶匿名墙</title>\n");
      out.write("    <style>\n");
      out.write("        :root {\n");
      out.write("            --glass-bg: rgba(255, 255, 255, 0.18);\n");
      out.write("            --glass-border: rgba(255, 255, 255, 0.35);\n");
      out.write("            --text-primary: #1f2937;\n");
      out.write("            --text-subtle: #4b5563;\n");
      out.write("            --bg-gradient: linear-gradient(135deg, #dbeafe 0%, #ede9fe 35%, #fce7f3 100%);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        * { box-sizing: border-box; }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            margin: 0;\n");
      out.write("            min-height: 100vh;\n");
      out.write("            font-family: -apple-system, BlinkMacSystemFont, \"SF Pro Text\", \"Segoe UI\", sans-serif;\n");
      out.write("            color: var(--text-primary);\n");
      out.write("            background: var(--bg-gradient);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .page {\n");
      out.write("            max-width: 920px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("            padding: 28px 16px 36px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .glass {\n");
      out.write("            background: var(--glass-bg);\n");
      out.write("            border: 1px solid var(--glass-border);\n");
      out.write("            border-radius: 22px;\n");
      out.write("            backdrop-filter: blur(20px) saturate(1.2);\n");
      out.write("            -webkit-backdrop-filter: blur(20px) saturate(1.2);\n");
      out.write("            box-shadow: 0 12px 36px rgba(31, 41, 55, 0.12);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero {\n");
      out.write("            padding: 20px;\n");
      out.write("            margin-bottom: 16px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero h1 {\n");
      out.write("            margin: 0 0 6px;\n");
      out.write("            font-size: 26px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .subtle {\n");
      out.write("            color: var(--text-subtle);\n");
      out.write("            margin: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .top-bar {\n");
      out.write("            margin-top: 14px;\n");
      out.write("            display: flex;\n");
      out.write("            gap: 10px;\n");
      out.write("            flex-wrap: wrap;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: space-between;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .actions a, .actions button {\n");
      out.write("            text-decoration: none;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.5);\n");
      out.write("            color: #111827;\n");
      out.write("            background: rgba(255, 255, 255, 0.35);\n");
      out.write("            border-radius: 999px;\n");
      out.write("            padding: 8px 14px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .panel {\n");
      out.write("            padding: 16px;\n");
      out.write("            margin-bottom: 16px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .filter-form {\n");
      out.write("            margin: 8px 0 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        textarea, select {\n");
      out.write("            width: 100%;\n");
      out.write("            margin-top: 6px;\n");
      out.write("            border-radius: 14px;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.7);\n");
      out.write("            background: rgba(255, 255, 255, 0.78);\n");
      out.write("            padding: 10px 12px;\n");
      out.write("            color: #111827;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .row {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: 1fr 180px;\n");
      out.write("            gap: 12px;\n");
      out.write("            margin-top: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .note-list {\n");
      out.write("            display: grid;\n");
      out.write("            gap: 12px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .note {\n");
      out.write("            border-radius: 18px;\n");
      out.write("            padding: 14px;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.55);\n");
      out.write("            background: rgba(255, 255, 255, 0.7);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .note-calm { background: linear-gradient(135deg, rgba(209, 250, 229, 0.85), rgba(240, 253, 250, 0.9)); }\n");
      out.write("        .note-happy { background: linear-gradient(135deg, rgba(254, 240, 138, 0.82), rgba(254, 249, 195, 0.92)); }\n");
      out.write("        .note-sad { background: linear-gradient(135deg, rgba(191, 219, 254, 0.82), rgba(224, 242, 254, 0.92)); }\n");
      out.write("        .note-angry { background: linear-gradient(135deg, rgba(254, 202, 202, 0.82), rgba(254, 226, 226, 0.92)); }\n");
      out.write("        .note-anxious { background: linear-gradient(135deg, rgba(221, 214, 254, 0.82), rgba(237, 233, 254, 0.92)); }\n");
      out.write("        .note-tired { background: linear-gradient(135deg, rgba(229, 231, 235, 0.85), rgba(243, 244, 246, 0.92)); }\n");
      out.write("\n");
      out.write("        .note-head {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            margin-bottom: 8px;\n");
      out.write("            color: var(--text-subtle);\n");
      out.write("            font-size: 13px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .note-content {\n");
      out.write("            margin: 0 0 10px;\n");
      out.write("            white-space: pre-wrap;\n");
      out.write("            word-break: break-word;\n");
      out.write("            line-height: 1.55;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .danger-btn {\n");
      out.write("            border: none;\n");
      out.write("            background: rgba(239, 68, 68, 0.14);\n");
      out.write("            color: #b91c1c;\n");
      out.write("            border-radius: 999px;\n");
      out.write("            padding: 7px 12px;\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .flash {\n");
      out.write("            margin-bottom: 14px;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            padding: 10px 12px;\n");
      out.write("            background: rgba(16, 185, 129, 0.16);\n");
      out.write("            color: #065f46;\n");
      out.write("            border: 1px solid rgba(16, 185, 129, 0.25);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @media (max-width: 720px) {\n");
      out.write("            .row { grid-template-columns: 1fr; }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"page\">\n");

    Object flash = request.getAttribute("flashMessage");
    String csrfToken = (String) request.getAttribute("csrfToken");
    String username = (String) request.getAttribute("username");
    String mode = (String) request.getAttribute("mode");
    String moodFilter = (String) request.getAttribute("moodFilter");
    String moodQuery = "";
    if (moodFilter != null && !moodFilter.isEmpty()) {
        try {
            moodQuery = "&mood=" + URLEncoder.encode(moodFilter, "UTF-8");
        } catch (Exception ignored) {
            // UTF-8 is always supported; fallback to no filter query if unexpected errors happen.
            moodQuery = "";
        }
    }
    List<StudentRecord> records = (List<StudentRecord>) request.getAttribute("records");

      out.write("\n");
      out.write("    <div class=\"hero glass\">\n");
      out.write("        <h1>情绪垃圾桶 · 匿名墙</h1>\n");
      out.write("        <p class=\"subtle\">把情绪写下来，轻轻放下。墙上只显示内容与心情色块，不显示发布者身份。</p>\n");
      out.write("        <div class=\"top-bar\">\n");
      out.write("            <p class=\"subtle\">已登录：<strong>");
      out.print( HtmlEscapeUtil.escape(username) );
      out.write("</strong></p>\n");
      out.write("            <div class=\"actions\">\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/records?mode=timeline");
      out.print( moodQuery );
      out.write("\">时间轴</a>\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/records?mode=random");
      out.print( moodQuery );
      out.write("\">随机流</a>\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/logout\">退出</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"panel glass\">\n");
      out.write("        <form method=\"post\" action=\"");
      out.print( request.getContextPath() );
      out.write("/records\">\n");
      out.write("            <input type=\"hidden\" name=\"csrfToken\" value=\"");
      out.print( HtmlEscapeUtil.escape(csrfToken) );
      out.write("\" />\n");
      out.write("            <input type=\"hidden\" name=\"action\" value=\"add\" />\n");
      out.write("            <label for=\"content\">写下这一刻（最多 280 字）</label>\n");
      out.write("            <textarea id=\"content\" name=\"content\" maxlength=\"280\" rows=\"4\" required placeholder=\"我想说...\"></textarea>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div>\n");
      out.write("                    <label for=\"mood\">心情颜色</label>\n");
      out.write("                    <select id=\"mood\" name=\"mood\" required>\n");
      out.write("                        <option value=\"calm\">平静</option>\n");
      out.write("                        <option value=\"happy\">开心</option>\n");
      out.write("                        <option value=\"sad\">低落</option>\n");
      out.write("                        <option value=\"angry\">生气</option>\n");
      out.write("                        <option value=\"anxious\">焦虑</option>\n");
      out.write("                        <option value=\"tired\">疲惫</option>\n");
      out.write("                    </select>\n");
      out.write("                </div>\n");
      out.write("                <div style=\"display:flex;align-items:flex-end;\">\n");
      out.write("                    <button type=\"submit\">投递纸条</button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");

        if (flash != null) {
    
      out.write("\n");
      out.write("    <div class=\"flash\">");
      out.print( HtmlEscapeUtil.escape(flash.toString()) );
      out.write("</div>\n");
      out.write("    ");

        }
    
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"panel glass\">\n");
      out.write("        <p class=\"subtle\" style=\"margin-top:0;\">\n");
      out.write("            当前查看：<strong>");
      out.print( "random".equals(mode) ? "随机流" : "时间轴" );
      out.write("</strong>\n");
      out.write("        </p>\n");
      out.write("        <form method=\"get\" action=\"");
      out.print( request.getContextPath() );
      out.write("/records\" class=\"filter-form\">\n");
      out.write("            <input type=\"hidden\" name=\"mode\" value=\"");
      out.print( HtmlEscapeUtil.escape(mode) );
      out.write("\" />\n");
      out.write("            <label for=\"filterMood\">按心情筛选</label>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div>\n");
      out.write("                    <select id=\"filterMood\" name=\"mood\">\n");
      out.write("                        <option value=\"\" ");
      out.print( (moodFilter == null || moodFilter.isEmpty()) ? "selected" : "" );
      out.write(">全部</option>\n");
      out.write("                        <option value=\"calm\" ");
      out.print( "calm".equals(moodFilter) ? "selected" : "" );
      out.write(">平静</option>\n");
      out.write("                        <option value=\"happy\" ");
      out.print( "happy".equals(moodFilter) ? "selected" : "" );
      out.write(">开心</option>\n");
      out.write("                        <option value=\"sad\" ");
      out.print( "sad".equals(moodFilter) ? "selected" : "" );
      out.write(">低落</option>\n");
      out.write("                        <option value=\"angry\" ");
      out.print( "angry".equals(moodFilter) ? "selected" : "" );
      out.write(">生气</option>\n");
      out.write("                        <option value=\"anxious\" ");
      out.print( "anxious".equals(moodFilter) ? "selected" : "" );
      out.write(">焦虑</option>\n");
      out.write("                        <option value=\"tired\" ");
      out.print( "tired".equals(moodFilter) ? "selected" : "" );
      out.write(">疲惫</option>\n");
      out.write("                    </select>\n");
      out.write("                </div>\n");
      out.write("                <div style=\"display:flex;align-items:flex-end;\">\n");
      out.write("                    <button type=\"submit\">应用筛选</button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("        <div class=\"note-list\">\n");
      out.write("            ");

                if (records != null && !records.isEmpty()) {
                    for (StudentRecord note : records) {
                        String mood = note.getMood();
                        String moodClass;
                        if ("happy".equals(mood)) {
                            moodClass = "note-happy";
                        } else if ("sad".equals(mood)) {
                            moodClass = "note-sad";
                        } else if ("angry".equals(mood)) {
                            moodClass = "note-angry";
                        } else if ("anxious".equals(mood)) {
                            moodClass = "note-anxious";
                        } else if ("tired".equals(mood)) {
                            moodClass = "note-tired";
                        } else {
                            moodClass = "note-calm";
                        }
                        boolean own = username != null && username.equals(note.getOwnerUsername());
            
      out.write("\n");
      out.write("            <article class=\"note ");
      out.print( moodClass );
      out.write("\">\n");
      out.write("                <div class=\"note-head\">\n");
      out.write("                    <span>#匿名纸条 · ");
      out.print( HtmlEscapeUtil.escape(note.getCreatedAt()) );
      out.write("</span>\n");
      out.write("                    <span>");
      out.print( HtmlEscapeUtil.escape(note.getMood()) );
      out.write("</span>\n");
      out.write("                </div>\n");
      out.write("                <p class=\"note-content\">");
      out.print( HtmlEscapeUtil.escape(note.getContent()) );
      out.write("</p>\n");
      out.write("                ");

                    if (own) {
                
      out.write("\n");
      out.write("                <form method=\"post\" action=\"");
      out.print( request.getContextPath() );
      out.write("/records\">\n");
      out.write("                    <input type=\"hidden\" name=\"csrfToken\" value=\"");
      out.print( HtmlEscapeUtil.escape(csrfToken) );
      out.write("\" />\n");
      out.write("                    <input type=\"hidden\" name=\"action\" value=\"delete\" />\n");
      out.write("                    <input type=\"hidden\" name=\"id\" value=\"");
      out.print( note.getId() );
      out.write("\" />\n");
      out.write("                    <button class=\"danger-btn\" type=\"submit\" onclick=\"return confirm('确认撤回这条纸条？');\">撤回我的纸条</button>\n");
      out.write("                </form>\n");
      out.write("                ");

                    }
                
      out.write("\n");
      out.write("            </article>\n");
      out.write("            ");

                    }
                } else {
            
      out.write("\n");
      out.write("            <p class=\"subtle\">还没有纸条，试着投递第一条吧。</p>\n");
      out.write("            ");

                }
            
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
